---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 2
    schedule:
      interval: weekly
    labels:
      - "ignore-for-release"
    commit-message:
      prefix: chore(ci)
  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
      time: "23:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: chore
      include: "scope"
    groups:
      golang-org-x:
        patterns:
          - "golang.org/x/*"
  - package-ecosystem: gomod
    directory: /example
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
      time: "23:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: chore
      include: "scope"
    groups:
      golang-org-x:
        patterns:
          - "golang.org/x/*"
  - package-ecosystem: gomod
    directory: /test
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
      time: "23:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: chore
      include: "scope"
    groups:
      golang-org-x:
        patterns:
          - "golang.org/x/*"
  - package-ecosystem: docker
    directory: /example/consumer
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
      time: "23:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: chore
      include: "scope"
    groups:
      golang-org-x:
        patterns:
          - "golang.org/x/*"
  - package-ecosystem: docker
    directory: /example/producer
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
      time: "23:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: chore
      include: "scope"
    groups:
      golang-org-x:
        patterns:
          - "golang.org/x/*"
